@startuml FirstAct

left to right direction

rectangle ファーストアクト集約 {
    object ファーストアクト
}

object ファーストアクト {
    + ファーストアクトID
    + 使用済みダイスIDとシンボル
    + 使うダイスIDとシンボル
    + 未使用のダイスIDとシンボル
    + アクトタイトル
    + アクトセンテンス
    + アクトイラスト
}

note right of ファーストアクト
・使用済みダイス数は0
・使うダイス数は3
・未使用のダイス数は6
・ダイスは重複しない
end note

rectangle ミドルアクト集約 {
    object ミドルアクト
}

object ミドルアクト {
    + ミドルアクトID
    + 使用済みダイスIDとシンボル
    + 使うダイスIDとシンボル
    + 未使用のダイスIDとシンボル
    + アクトセンテンス
    + アクトイラスト
}

note right of ミドルアクト
・使用済みダイス数は3
・使うダイス数は3
・未使用のダイス数は3
・ダイスは重複しない
end note

object アクトタイトル {
    + タイトル名
}
ファーストアクト --> アクトタイトル
ミドルアクト --> アクトタイトル
note right of アクトタイトル
・タイトル名の長さは、1~20文字
end note

object アクトセンテンス {
    + センテンス内容
}
ファーストアクト --> アクトセンテンス
ミドルアクト --> アクトセンテンス
note right of アクトセンテンス
・センテンス内容の長さは、1~400文字
end note

object アクトイラスト {
    + イラスト内容
}
ファーストアクト --> アクトイラスト
ミドルアクト --> アクトイラスト
note right of アクトイラスト
・イラスト内容は、縦横の幅の最大値がある(未定)
・イラスト内容は、サイズの最大値がある(未定)
end note

rectangle ダイス集約 {
    object ダイス
    object シンボル
    ファーストアクト -up-> ダイス
    ミドルアクト -up-> ダイス
    シンボル -left-* ダイス
}

object ダイス {
    + ダイスID
    + シンボルのリスト
}

note left of ダイス 
・シンボルは6つ
end note

object シンボル {
    + シンボルID
    + シンボルイラスト
}

note left of シンボル
・シンボルイラストは、縦横の比が同一かつ固定
・シンボルイラストは、サイズの最大値がある(未定)
end note

@enduml