@startuml FirstAct

rectangle ファーストアクト集約 {
    object ファーストアクト
}

object ファーストアクト {
    - 利用するダイスIDとシンボルイラストのリスト
    - 未使用のダイスIDとシンボルイラストのリスト
    + アクトID
    + 利用するシンボルイラストのリスト
    + 未使用のシンボルイラストのリスト
    + アクトタイトル
    + アクトセンテンス
    + アクトイラスト
}

note right of ファーストアクト
・使うダイス数は3つ
・未使用のダイスは6つ
・使うダイスと未使用のダイスには重複がない
・アクトタイトルは、1~20文字（コードポイント）
・アクトセンテンスは、1~400文字
・アクトイラストは、縦横の幅の最大値がある(未定)
・アクトイラストは、サイズの最大値がある(未定)
end note

rectangle ダイス集約 {
    object ダイス
    object シンボル
    ファーストアクト --> ダイス
    シンボル -left-* ダイス
}

object ダイス {
    + ダイスID
    + シンボルのリスト
}

note bottom of ダイス 
・シンボルは6つ
end note

object シンボル {
    + シンボルID
    + ダイスID
    + シンボルイラスト
}

note bottom of シンボル
・シンボルイラストは、縦横の比が同一かつ固定
・シンボルイラストは、サイズの最大値がある(未定)
end note

@enduml