@startuml writeFirstAct

left to right direction

actor user

rectangle WriteFirstAct {
    user -- (rollDice)
    user -- (chooseDice)
    user -- (decideTitle)
    user -- (writeSentence)
    user -- (addIllustration)    
    user -- (postAct)
    (chooseDice) ..> (postAct) : include
    (decideTitle) ..> (postAct) : include
    (writeSentence) ..> (postAct) : include
    (addIllustration) ..> (postAct) : include
}

@enduml